var tileMap = [
  //[["Mud","Mud","Mud","Mud","Mud","Mud","Mud","Mud","Mud"],["Mud","Wall","Wall","Pit","Pit","Pit","Wall","Wall","Mud"],["Mud","Wall","Water","Water","Water","Water","Water","Wall","Mud"],["Mud","Pit","Water","Trap","Trap","Trap","Water","Pit","Mud"],["Mud","Floor","Water","Trap","Chest","Trap","Water","Pit","Mud"],["Mud","Pit","Water","Trap","Trap","Trap","Water","Pit","Mud"],["Mud","Wall","Water","Water","Water","Water","Water","Wall","Mud"],["Mud","Wall","Wall","Pit","Pit","Pit","Wall","Wall","Mud"],["Mud","Mud","Mud","Mud","Mud","Mud","Mud","Mud","Mud"]]
  [["Mud","Mud","Mud","Mud","Mud","Mud","Mud","Mud"],["Mud","Wall","Wall","Pit","Pit","Pit","Wall","Wall"],["Mud","Wall","Water","Water","Floor","Water","Water","Wall"],["Mud","Pit","Water","Trap","Trap","Trap","Water","Pit"],["Mud","Floor","Floor","Trap","Chest","Trap","Water","Pit"],["Mud","Pit","Water","Trap","Trap","Trap","Water","Pit"],["Mud","Wall","Water","Water","Water","Water","Water","Wall"],["Mud","Wall","Wall","Pit","Pit","Pit","Wall","Wall"]],
  [["Floor","Wall","Wall","Floor","Floor","Floor","Floor","Floor"],["Wall","Wall","Wall","Floor","Floor","Floor","Wall","Wall"],["Wall","Wall","Floor","Floor","Floor","Wall","Wall","Wall"],["Floor","Floor","Floor","Floor","Floor","Wall","Wall","Floor"],["Floor","Floor","Floor","Floor","Wall","Wall","Wall","Floor"],["Wall","Wall","Floor","Wall","Wall","Wall","Floor","Floor"],["Wall","Wall","Wall","Wall","Wall","Floor","Floor","Floor"],["Floor","Wall","Wall","Wall","Floor","Floor","Floor","Floor"]],
  [["Floor","Wall","Wall","Wall","Wall","Wall","Wall","Floor"],["Wall","Wall","Wall","Floor","Floor","Wall","Wall","Wall"],["Wall","Wall","Floor","Floor","Floor","Floor","Wall","Wall"],["Floor","Floor","Floor","Floor","Floor","Floor","Floor","Floor"],["Floor","Floor","Floor","Floor","Floor","Floor","Floor","Floor"],["Wall","Wall","Floor","Floor","Floor","Floor","Wall","Wall"],["Wall","Wall","Wall","Floor","Floor","Wall","Wall","Wall"],["Floor","Wall","Wall","Wall","Wall","Wall","Wall","Floor"]],
  [["Floor","Floor","Floor","Floor","Floor","Floor","Floor","Floor"],["Floor","Wall","Wall","Wall","Wall","Floor","Floor","Wall"],["Wall","Wall","Wall","Wall","Floor","Floor","Wall","Wall"],["Floor","Floor","Wall","Wall","Floor","Wall","Wall","Floor"],["Floor","Floor","Floor","Wall","Floor","Wall","Floor","Floor"],["Floor","Floor","Floor","Wall","Floor","Wall","Floor","Floor"],["Wall","Wall","Floor","Floor","Floor","Wall","Wall","Floor"],["Floor","Wall","Floor","Floor","Floor","Floor","Wall","Wall"]],
  [["Floor","Floor","Floor","Floor","Floor","Floor","Floor","Floor"],["Floor","Wall","Floor","Floor","Floor","Floor","Floor","Floor"],["Floor","Floor","Floor","Floor","Wall","Floor","Floor","Floor"],["Floor","Floor","Floor","Wall","Wall","Floor","Floor","Floor"],["Floor","Floor","Wall","Wall","Wall","Wall","Wall","Floor"],["Floor","Floor","Floor","Floor","Wall","Floor","Floor","Floor"],["Floor","Floor","Floor","Floor","Wall","Floor","Floor","Wall"],["Floor","Floor","Floor","Floor","Floor","Floor","Wall","Wall"]],
  [["Floor","Floor","Floor","Floor","Floor","Floor","Floor","Floor"],["Floor","Floor","Floor","Water","Water","Water","Floor","Floor"],["Floor","Floor","Water","Wall","Floor","Wall","Water","Floor"],["Floor","Floor","Water","Floor","Stairs_down","Floor","Water","Floor"],["Floor","Floor","Water","Wall","Floor","Wall","Water","Floor"],["Floor","Floor","Floor","Water","Water","Water","Floor","Floor"],["Floor","Floor","Floor","Floor","Floor","Floor","Floor","Floor"],["Floor","Floor","Floor","Floor","Floor","Floor","Floor","Floor"]],
  [["Floor","Wall","Wall","Wall","Wall","Wall","SpawnerWall","Floor"],["Floor","Wall","Floor","Floor","Floor","Floor","Floor","Floor"],["Floor","Wall","Floor","SpawnerWall","Wall","Wall","SpawnerWall","Wall"],["Floor","Wall","Floor","Wall","Chest","Floor","Floor","Wall"],["Floor","Wall","Floor","SpawnerWall","Wall","SpawnerWall","Floor","Wall"],["Floor","Wall","Floor","Floor","Floor","Floor","Floor","Wall"],["Floor","SpawnerWall","Wall","Wall","Wall","Wall","Wall","Wall"],["Floor","Floor","Floor","Floor","Floor","Floor","Floor","Floor"]]
];
