var tileMap = [
  [["Floor","Floor","Floor","Floor","Floor","Floor","Floor","Floor"],["Floor","Wall","Floor","Floor","Floor","Floor","Floor","Floor"],["Floor","Floor","Floor","Floor","Wall","Floor","Floor","Floor"],["Floor","Floor","Floor","Wall","Wall","Floor","Floor","Floor"],["Floor","Floor","Wall","Wall","Wall","Wall","Wall","Floor"],["Floor","Floor","Floor","Floor","Wall","Floor","Floor","Floor"],["Floor","Floor","Floor","Floor","Wall","Floor","Floor","Wall"],["Floor","Floor","Floor","Floor","Floor","Floor","Wall","Wall"]],
  // slightly more effort
  [["Floor","Floor","Floor","Floor","Floor","Floor","Floor","Floor"],["Floor","Floor","SpawnerWall","Wall","Wall","Wall","SpawnerWall","Floor"],["Floor","Floor","Wall","Floor","Floor","Floor","Wall","Floor"],["Floor","Floor","Wall","Pit","SpawnerWall","Mud","Wall","Floor"],["Floor","Floor","SpawnerWall","Wall","SpawnerWall","Mud","Wall","Floor"],["Floor","Floor","Floor","Floor","Mud","Mud","Wall","Floor"],["Floor","Wall","Wall","Wall","Wall","Wall","SpawnerWall","Floor"],["Floor","Floor","Floor","Floor","Floor","Floor","Floor","Floor"]],
  [["Floor","Floor","Floor","Floor","Floor","Floor","Floor","Floor"],["Floor","Wall","Wall","Wall","Wall","Wall","Wall","Floor"],["Floor","Wall","Floor","Floor","Floor","Floor","Wall","Floor"],["Floor","Wall","Floor","SpawnerWall","Wall","Floor","Floor","Floor"],["Floor","Wall","Floor","SpawnerWall","Wall","Floor","Floor","Wall"],["Floor","Wall","Floor","Floor","Floor","Floor","Wall","Wall"],["Floor","Wall","Wall","Wall","Wall","Wall","Wall","Floor"],["Floor","Floor","Floor","Floor","Floor","Floor","Floor","Floor"]],
  [["Floor","Floor","Floor","Trap","Trap","Trap","Trap","Trap"],["Floor","Floor","Floor","Trap","Wall","Wall","Wall","Trap"],["Floor","Floor","Floor","Wall","Wall","Mud","SpawnerWall","Floor"],["Trap","Trap","Wall","Wall","Mud","Mud","Mud","Floor"],["Trap","Wall","Wall","Mud","Mud","SpawnerWall","Mud","Floor"],["Trap","Wall","Wall","Mud","Wall","Wall","Wall","Floor"],["Trap","Wall","Wall","Mud","Wall","Floor","SpawnerWall","Floor"],["Trap","Floor","Mud","Mud","Wall","Floor","Floor","Floor"]],
  [["Floor","Floor","Floor","Floor","Floor","Floor","Floor","Floor"],["Floor","Floor","Wall","Wall","Wall","Wall","Wall","Floor"],["Floor","Floor","Wall","Floor","Hazard","Floor","Wall","Floor"],["Floor","Floor","Wall","Hazard","Wall","Hazard","Wall","Floor"],["Floor","Floor","Wall","Floor","Wall","Floor","Wall","Floor"],["Floor","Floor","SpawnerWall","Floor","Wall","Chest","Wall","Floor"],["Floor","Floor","Floor","Floor","Wall","Wall","Wall","Floor"],["Floor","Floor","Floor","Floor","Floor","Floor","Floor","Floor"]],
  [["Floor","Floor","Floor","Floor","Floor","Floor","Floor","Floor"],["Floor","Floor","Wall","Wall","Wall","Floor","Floor","Floor"],["Floor","Mud","Mud","Mud","Mud","Mud","Floor","Floor"],["Wall","Mud","SpawnerWall","Mud","SpawnerWall","Mud","Wall","Floor"],["Wall","Mud","Mud","SpawnerWall","Mud","Mud","Wall","Floor"],["Wall","Mud","SpawnerWall","Mud","SpawnerWall","Mud","Wall","Floor"],["Floor","Mud","Mud","Mud","Mud","Mud","Floor","Floor"],["Floor","Floor","Wall","Wall","Wall","Floor","Floor","Floor"]]
];

var tileMap_down = [
  [["Floor","Floor","Floor","Floor","Floor","Floor","Floor","Floor"],["Floor","Floor","Floor","Water","Water","Water","Floor","Floor"],["Floor","Floor","Water","Wall","Floor","Wall","Water","Floor"],["Floor","Floor","Water","Floor","Stairs_down","Floor","Water","Floor"],["Floor","Floor","Water","Wall","Floor","Wall","Water","Floor"],["Floor","Floor","Floor","Water","Water","Water","Floor","Floor"],["Floor","Floor","Floor","Floor","Floor","Floor","Floor","Floor"],["Floor","Floor","Floor","Floor","Floor","Floor","Floor","Floor"]]
]